name: FDH_tutorial_CV_DL
channels:
  - defaults
dependencies:
  - _tflow_1100_select=0.0.2=eigen
  - absl-py=0.4.1=py35_0
  - appdirs=1.4.3=py35h28b3542_0
  - appnope=0.1.0=py35hd172556_0
  - asn1crypto=0.24.0=py35_0
  - astor=0.7.1=py35_0
  - attrs=18.2.0=py35h28b3542_0
  - automat=0.7.0=py35_0
  - backcall=0.1.0=py35_0
  - blas=1.0=mkl
  - bleach=2.1.4=py35_0
  - ca-certificates=2018.03.07=0
  - certifi=2018.8.24=py35_1
  - cffi=1.11.5=py35h6174b99_1
  - cloudpickle=0.5.5=py35_0
  - constantly=15.1.0=py35h28b3542_0
  - cryptography=2.3.1=py35hdbc3d79_0
  - cycler=0.10.0=py35hb89929e_0
  - dask-core=0.19.2=py35_0
  - dbus=1.13.2=h760590f_1
  - decorator=4.3.0=py35_0
  - defusedxml=0.5.0=py35_1
  - entrypoints=0.2.3=py35_2
  - expat=2.2.6=h0a44026_0
  - freetype=2.9.1=hb4e5f40_0
  - gast=0.2.0=py35_0
  - gettext=0.19.8.1=h15daf44_3
  - glib=2.56.2=hd9629dc_0
  - grpcio=1.12.1=py35hd9629dc_0
  - h5py=2.8.0=py35h878fce3_3
  - hdf5=1.10.2=hfa1e0ec_1
  - html5lib=1.0.1=py35_0
  - hyperlink=18.0.0=py35_0
  - icu=58.2=h4b95b61_1
  - idna=2.7=py35_0
  - imageio=2.4.1=py35_0
  - incremental=17.5.0=py35_0
  - intel-openmp=2019.0=118
  - ipykernel=4.10.0=py35_0
  - ipython=6.5.0=py35_0
  - ipython_genutils=0.2.0=py35hf129286_0
  - ipywidgets=7.4.1=py35_0
  - jbig=2.1=h4d881f8_0
  - jedi=0.12.1=py35_0
  - jinja2=2.10=py35_0
  - jpeg=9b=he5867d9_2
  - jsonschema=2.6.0=py35h2dd9e4b_0
  - jupyter=1.0.0=py35_7
  - jupyter_client=5.2.3=py35_0
  - jupyter_console=5.2.0=py35hd2aa692_1
  - jupyter_core=4.4.0=py35_0
  - kiwisolver=1.0.1=py35h219a9d8_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20170329=hb402a30_2
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libiconv=1.15=hdd342a3_7
  - libpng=1.6.35=ha441bb4_0
  - libprotobuf=3.6.0=hd9629dc_0
  - libsodium=1.0.16=h3efe00b_0
  - libtiff=4.0.9=hcb84e12_2
  - markdown=2.6.11=py35_0
  - markupsafe=1.0=py35h1de35cc_1
  - matplotlib=3.0.0=py35h54f8f79_0
  - mistune=0.8.3=py35h1de35cc_1
  - mkl=2019.0=118
  - mkl_fft=1.0.6=py35hb8a8100_0
  - mkl_random=1.0.1=py35h5d10147_1
  - nbconvert=5.4.0=py35_1
  - nbformat=4.4.0=py35h41c2038_0
  - ncurses=6.1=h0a44026_0
  - networkx=2.1=py35_0
  - notebook=5.6.0=py35_0
  - numpy=1.15.2=py35h6a91979_0
  - numpy-base=1.15.2=py35h8a80b8c_0
  - olefile=0.46=py35_0
  - openssl=1.0.2p=h1de35cc_0
  - pandoc=1.19.2.1=ha5e8f32_1
  - pandocfilters=1.4.2=py35_1
  - parso=0.3.1=py35_0
  - path.py=11.1.0=py35_0
  - pcre=8.42=h378b8a2_0
  - pexpect=4.6.0=py35_0
  - pickleshare=0.7.4=py35h9517181_0
  - pillow=5.2.0=py35hb68e598_0
  - pip=10.0.1=py35_0
  - prometheus_client=0.3.1=py35h28b3542_0
  - prompt_toolkit=1.0.15=py35h93950c5_0
  - protobuf=3.6.0=py35h0a44026_0
  - ptyprocess=0.6.0=py35_0
  - pyasn1=0.4.4=py35h28b3542_0
  - pyasn1-modules=0.2.2=py35_0
  - pycparser=2.19=py35_0
  - pygments=2.2.0=py35h392a662_0
  - pyopenssl=18.0.0=py35_0
  - pyparsing=2.2.1=py35_0
  - pyqt=5.9.2=py35h655552a_2
  - python=3.5.6=hc167b69_0
  - python-dateutil=2.7.3=py35_0
  - pytz=2018.5=py35_0
  - pywavelets=1.0.0=py35h1d22016_0
  - pyzmq=17.1.2=py35h1de35cc_0
  - qt=5.9.6=h45cd832_2
  - qtconsole=4.4.1=py35_0
  - readline=7.0=h1de35cc_5
  - scikit-image=0.14.0=py35h0a44026_1
  - scikit-learn=0.20.0=py35h4f467ca_1
  - scipy=1.1.0=py35h28f7352_1
  - send2trash=1.5.0=py35_0
  - service_identity=17.0.0=py35h28b3542_0
  - setuptools=40.2.0=py35_0
  - simplegeneric=0.8.1=py35_2
  - sip=4.19.8=py35h0a44026_0
  - six=1.11.0=py35_1
  - sqlite=3.25.2=ha441bb4_0
  - tensorboard=1.10.0=py35hdc36e2c_0
  - tensorflow=1.10.0=eigen_py35h5ac2770_0
  - tensorflow-base=1.10.0=eigen_py35h4f0eeca_0
  - termcolor=1.1.0=py35_1
  - terminado=0.8.1=py35_1
  - testpath=0.3.1=py35hf8009f4_0
  - tk=8.6.8=ha441bb4_0
  - toolz=0.9.0=py35_0
  - tornado=5.1.1=py35h1de35cc_0
  - tqdm=4.26.0=py35h28b3542_0
  - traitlets=4.3.2=py35hd3d1486_0
  - twisted=17.5.0=py35_0
  - wcwidth=0.1.7=py35hdd0c235_0
  - webencodings=0.5.1=py35_1
  - werkzeug=0.14.1=py35_0
  - wheel=0.31.1=py35_0
  - widgetsnbextension=3.4.1=py35_0
  - xz=5.2.4=h1de35cc_4
  - zeromq=4.2.5=h0a44026_1
  - zlib=1.2.11=hf3cbc9b_2
  - zope=1.0=py35_1
  - zope.interface=4.5.0=py35h1de35cc_0
  - pip:
    - dask==0.19.2
    - dlib==19.16.0
    - keras==2.0.9
    - pyyaml==3.12

